CREATE TABLE IF NOT EXISTS accounts (
                          id varchar(255) not null,
                          active boolean not null,
                          credit_card_number varchar(255),
                          email varchar(255),
                          firstname varchar(255),
                          lastname varchar(255),
                          amount numeric(19, 2),
                          primary key (id)
);

CREATE TABLE IF NOT EXISTS auctions (
                          id uuid not null,
                          name varchar(255),
                          duration double precision,
                          isclosed boolean not null,
                          item uuid,
                          min_increment numeric(19, 2),
                          seller varchar(255),
                          start_price numeric(19, 2),
                          auction_start_time TIMESTAMP,
                          primary key (id)
);

CREATE TABLE IF NOT EXISTS accounts_auctions (
                                   account_id varchar(255) not null,
                                   auctions uuid
);



CREATE TABLE IF NOT EXISTS bids (
                      id uuid not null,
                      amount numeric(19, 2),
                      buyer varchar(255),
                      date timestamp,
                      primary key (id)
);

CREATE TABLE IF NOT EXISTS credit_card (
                             number varchar(255) not null,
                             city varchar(255),
                             country varchar(255),
                             postal_code varchar(255),
                             street varchar(255),
                             account_firstname varchar(255),
                             account_lastname varchar(255),
                             expiration_month smallint,
                             expiration_year smallint,
                             primary key (number)
);

CREATE TABLE IF NOT EXISTS items (
                       id uuid not null,
                       description varchar(255),
                       image oid,
                       title varchar(255),
                       primary key (id)
);

CREATE TABLE IF NOT EXISTS users (
                       id integer generated by default as identity,
                       enabled boolean not null,
                       password varchar(120),
                       role varchar(255),
                       username varchar(20),
                       primary key (id)
);

CREATE TABLE IF NOT EXISTS accounts_bids (
                               account_id varchar(255) not null,
                               bids uuid
);


CREATE TABLE IF NOT EXISTS auctions_bids (
                               auction_id uuid not null,
                               bids uuid
);

alter table if exists users
    drop constraint if exists UsernameUnique;

alter table if exists accounts_auctions
    drop constraint if exists AccountsAuctionsAccountsKey;

alter table if exists accounts_bids
    drop constraint if exists AccountsBidsAccountsKey;

alter table if exists auctions_bids
    drop constraint if exists AccountsBidsAuctionsKey;

alter table if exists users
    add constraint UsernameUnique unique (username);

alter table if exists accounts_auctions
    add constraint AccountsAuctionsAccountsKey
        foreign key (account_id)
            references accounts;

alter table if exists accounts_bids
    add constraint AccountsBidsAccountsKey
        foreign key (account_id)
            references accounts;

alter table if exists auctions_bids
    add constraint AccountsBidsAuctionsKey
        foreign key (auction_id)
            references auctions;
